// This file is automatically generated. Do not edit it directly.
import { Client, TablesDB, Account, Teams } from "appwrite";
const client = new Client();
client
  .setEndpoint("https://fra.cloud.appwrite.io/v1")
  .setProject("68ac6ba8000601f31e0d");

export const account = new Account(client);
export const tablesDB = new TablesDB(client);
